### ISSUE TITLE
also add hex representation

### ISSUE THREAD

**Issue by tessus** [ba9f11ecc3497d9993b933fdc2bd61e5/ipcalc6#1] opened 2023-02-27 02:49 UTC
This is a great tool, but it would be great, if it also showed the addresses as hex.

e.g. ipcalc does this:

```
$ ipcalc 192.168.1.1/24
Address:   192.168.1.1          11000000.10101000.00000001. 00000001
Netmask:   255.255.255.0 = 24   11111111.11111111.11111111. 00000000
Wildcard:  0.0.0.255            00000000.00000000.00000000. 11111111
=>
Network:   192.168.1.0/24       11000000.10101000.00000001. 00000000
HostMin:   192.168.1.1          11000000.10101000.00000001. 00000001
HostMax:   192.168.1.254        11000000.10101000.00000001. 11111110
Broadcast: 192.168.1.255        11000000.10101000.00000001. 11111111
Hosts/Net: 254                   Class C, Private Internet
```

I know that it takes too much space for adding the addresses in hex next to the binary representation, but maybe it is possible to add it between `Hosts/Net` and `Address`.

```
$ ipcalc6 fddf:dead:1337:0::1/64

Type:		Unique-Local Address
Address:	fddf:dead:1337:0000:0000:0000:0000:0001		NetMask:	64
Hosts/Net:	147573952589676412928

Address:        fddf:dead:1337:0000:0000:0000:0000:0001
HostMin:        fddf:dead:1337:0000:0000:0000:0000:0000
HostMax:        fddf:dead:1337:0000:ffff:ffff:ffff:ffff

Address:	1111110111011111.1101111010101101.0001001100110111.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000001
NetMask:	1111111111111111.1111111111111111.1111111111111111.1111111111111111.0000000000000000.0000000000000000.0000000000000000.0000000000000000
HostMin:	1111110111011111.1101111010101101.0001001100110111.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000
HostMax:	1111110111011111.1101111010101101.0001001100110111.0000000000000000.1111111111111111.1111111111111111.1111111111111111.1111111111111111
```

What do you think?

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment] 2023-03-01 14:58
I added it... the hardest part was to colorize the hex representation. The approach I took is that as soon as a bit of the hex char is touched by the mask, it is colorized as being part of the subnet.

It was fun reopening this project, thanks.

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment] 2023-03-01 15:13
hmm, found a bug, hold on.

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment] 2023-03-01 17:11
was not a bug but a ugly logical error... fixed now. let me know

**Closed by ba9f11ecc3497d9993b933fdc2bd61e5** 2023-03-01 17:11 UTC

**Comment by tessus** [comment] 2023-03-01 20:26
This is awesome. Thanks, it works great. This should be included in Linux distros!

Btw, just out of curiosity, the ipcalc for ip4 has also the options `-r, --range` and `-s, --split`. Would they make sense in ipv6 as well? Personally I doubt it, since ipv6 already has huge ranges by default.

But these options would make sense:

```
 -n --nocolor  Don't display ANSI color codes.
 -b --nobinary Suppress the bitwise output.
```

Would you accept a PR? Although I think it would make sense to use a crate for argument parsing.

----

Please tell me, if I should open a separate issue for this (if you cansider this a bug that is). It always depends on the dev and project. Some say, they want new issues for every single thing. Others don't mind if new things are discussed in an "old" issue.

I have noticed a small peculiarity, but it is nothing huge:

```
ipcalc6 fddf:2233:4444::/8

WARNING : netmask /8 is smaller than /48, this is unusual if ip of type : Global Unicast Address and Link-Local Address
```

The address is neither a global unicast address, nor a link-local address.

Addresses starting with `fd` are unique local addresses, the address block for link-loca addresses is `fe80::/10`.

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment] 2023-03-02 07:51
I fixed the erroneous message for Unique Local address.

**Comment by tessus** [comment] 2023-03-02 23:28
Not quite. ;-)

```
error: comparison operators cannot be chained
  --> src/main.rs:97:17
   |
97 |     if int_mask >= 7 <= 128  {
   |                 ^^   ^^

error[E0308]: mismatched types
  --> src/main.rs:97:25
   |
97 |     if int_mask >= 7 <= 128  {
   |                         ^^^ expected `bool`, found integer

For more information about this error, try `rustc --explain E0308`.
error: could not compile `ipcalc6` due to 2 previous errors
```

It should be `if int_mask >= 7 && int_mask <= 128`

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment] 2023-03-03 07:23
oops, fixed

**Comment by tessus** [comment] 2023-03-03 07:32
I think, there is a slight issue with the netmask.

I'll open a new issue. I don't want to pollute this closed ticket with something else....
